files:
  - source: /app/core/src/main/resources/co/casterlabs/caffeinated/app/locale/en_US.json
    translation: /app/core/src/main/resources/co/casterlabs/caffeinated/app/locale/%locale_with_underscore%.json
