// Generated by dts-bundle-generator v9.5.1

export declare type EventHandlerCallback = (data: any | null | undefined) => void;
export declare type EventHandlerCallbackWildcard = (type: string, data: any | null | undefined) => void;
export declare type EventHandlerCallbackEither = EventHandlerCallback | EventHandlerCallbackWildcard;
declare const GLOBAL: {
	readonly store: {
		language: string;
		emojiProvider: string;
		theme: string[];
		appearance: string;
		zoom: number;
	};
	on(key: string, listener: (data: any | null | undefined) => void): (string | number)[];
	off: (type: string, callbackId: number) => void;
	get(key: string): any;
	localize(key: string, knownPlaceholders?: {}, knownComponents?: any[]): Promise<string>;
};
declare const GLOBAL$1: {
	on(type: string, handler: EventHandlerCallbackEither): void;
	readonly connectionId: string;
	readonly widgetData: any;
	readonly mode: string;
	getSetting(key: string): any;
	emit(type: string, data?: {}): void;
	getResource(resourceId: string): Promise<unknown>;
};
declare const GLOBAL$2: {
	readonly eventHistory: KoiEvent[];
	readonly viewers: Record<UserPlatform, User>;
	readonly viewerCounts: Record<UserPlatform, number>;
	readonly userStates: Record<UserPlatform, any>;
	readonly streamStates: Record<UserPlatform, any>;
	readonly roomStates: Record<UserPlatform, any>;
	readonly features: Record<UserPlatform, KoiIntegrationFeature[]>;
	upvoteChat(platform: UserPlatform, messageId: MessageId): void;
	deleteChat(platform: UserPlatform, messageId: MessageId, isUserGesture?: boolean): void;
	sendChat(platform: UserPlatform, message: MessageId, chatter?: 'SYSTEM' | 'CLIENT' | 'PUPPET', replyTarget?: MessageId | null, isUserGesture?: boolean): void;
};
export declare type KoiIntegrationFeature = string;
/**
 * Unique Platform Identifier. Guaranteed to be unique to the user even if two different platforms have ID collisions.
 */
export declare type UPID = string;
export declare type UserPlatform =
	| 'CAFFEINE'
	| 'TWITCH'
	| 'TROVO'
	| 'GLIMESH'
	| 'BRIME'
	| 'YOUTUBE'
	| 'DLIVE'
	| 'TIKTOK'
	| 'THETA'
	| 'KICK'
	| 'YOUNOW'
	| 'LIVESPACE'
	| 'NOICE'
	| 'X'
	| 'RUMBLE'
	| 'LOCO'
	| 'CASTERLABS_SYSTEM'
	| 'CUSTOM_INTEGRATION';
export declare type UserRole = 'BROADCASTER' | 'SUBSCRIBER' | 'FOLLOWER' | 'MODERATOR' | 'STAFF' | 'VIP' | 'OG';
export declare interface SimpleProfile {
	UPID: UPID;
	id: string;
	channel_id: string;
	platform: UserPlatform;
}
export declare interface User extends SimpleProfile {
	color: string;
	username: string;
	displayname: string;
	bio: string;
	link: string;
	image_link: string;
	followers_count: number;
	subscriber_count: number;
	roles: UserRole[];
	badges: string[];
}
export declare type KoiEvent =
	| CatchupEvent
	| ChannelPointsEvent
	| ClearChatEvent
	| ConnectionStateEvent
	| FollowEvent
	| LikeEvent
	| PlatformMessageEvent
	| RaidEvent
	| RichMessageEvent
	| RoomstateEvent
	| StreamStatusEvent
	| SubscriptionEvent
	| UserUpdateEvent
	| ViewerCountEvent
	| ViewerJoinLeaveEvent
	| ViewerJoinLeaveEvent
	| ViewerListEvent;
export declare type KoiEventType =
	| 'FOLLOW'
	| 'SUBSCRIPTION'
	| 'USER_UPDATE'
	| 'STREAM_STATUS'
	| 'META'
	| 'VIEWER_JOIN'
	| 'VIEWER_LEAVE'
	| 'VIEWER_LIST'
	| 'VIEWER_COUNT'
	| 'RAID'
	| 'CHANNEL_POINTS'
	| 'CATCHUP'
	| 'CLEARCHAT'
	| 'ROOMSTATE'
	| 'PLATFORM_MESSAGE'
	| 'RICH_MESSAGE'
	| 'LIKE'
	| 'CONNECTION_STATE';
export declare interface AbstractKoiEvent {
	streamer: SimpleProfile;
	timestamp: string;
	event_type: KoiEventType;
}
export declare interface CatchupEvent extends AbstractKoiEvent {
	event_type: 'CATCHUP';
	events: KoiEvent[];
}
export declare type ChannelPointsRewardEventId = string;
export declare type ChannelPointsRewardId = string;
export declare interface ChannelPointsRewardRedemption {
	id: ChannelPointsRewardId;
	title: string;
	cost: number;
	background_color: string;
	reward_image: string | null;
	default_reward_image: string;
	/**
	 * Null if disabled, see user_input.
	 */
	prompt: string | null;
	/**
	 * Null if disabled, see prompt.
	 */
	user_input: string | null;
}
export declare interface ChannelPointsEvent extends AbstractKoiEvent {
	event_type: 'CHANNEL_POINTS';
	sender: User;
	id: ChannelPointsRewardEventId;
	reward: ChannelPointsRewardRedemption;
}
export declare type ClearChatType = 'ALL' | 'USER';
export declare interface ClearChatEvent extends AbstractKoiEvent {
	event_type: 'CLEARCHAT';
	clear_type: ClearChatType;
	/**
	 * `null` if clearType == 'ALL'.
	 */
	user_upid: UPID | null;
}
export declare type ConnectionState = 'CONNECTED' | 'DISCONNECTED' | 'WAITING';
export declare interface ConnectionStateEvent extends AbstractKoiEvent {
	event_type: 'CONNECTION_STATE';
	states: {
		[key: string]: ConnectionState;
	};
}
export declare interface FollowEvent extends AbstractKoiEvent {
	event_type: 'FOLLOW';
	follower: User;
}
export declare interface LikeEvent extends AbstractKoiEvent {
	event_type: 'LIKE';
	/**
	 * May be `null` on platforms that do not tell us who liked.
	 */
	liker: User | null;
	total_likes: number;
}
export declare interface RaidEvent extends AbstractKoiEvent {
	event_type: 'RAID';
	host: User;
	/**
	 * May be 0 on platforms that do not expose this data.
	 */
	viewers: number;
}
export declare interface RoomstateEvent extends AbstractKoiEvent {
	event_type: 'ROOMSTATE';
	is_emote_only: boolean;
	is_subs_only: boolean;
	is_r9k: boolean;
	is_followers_only: boolean;
	is_slowmode: boolean;
}
export declare type ContentRating = 'FAMILY_FRIENDLY' | 'PG' | 'MATURE';
export declare interface StreamStatusEvent extends AbstractKoiEvent {
	event_type: 'STREAM_STATUS';
	is_live: boolean;
	title: string;
	start_time: string;
	tags: String[];
	category: string;
	contentRating: ContentRating;
	thumbnail_url: string;
	language: string;
}
export declare type SubscriptionType = 'SUB' | 'RESUB' | 'SUBGIFT' | 'RESUBGIFT' | 'ANONSUBGIFT' | 'ANONRESUBGIFT';
export declare type SubscriptionLevel = 'UNKNOWN' | 'TWITCH_PRIME' | 'TIER_1' | 'TIER_2' | 'TIER_3' | 'TIER_4' | 'TIER_5';
export declare interface SubscriptionEvent extends AbstractKoiEvent {
	event_type: 'SUBSCRIPTION';
	/**
	 * The user who paid for the subscription.
	 */
	subscriber: User;
	sub_type: SubscriptionType;
	sub_level: SubscriptionLevel;
	/**
	 * Null if not SUBGIFT or RESUBGIFT.
	 */
	gift_recipient: User;
	/**
	 * Note that this is unknowable on some platforms, like TikTok. In that case, it
	 * will always be 1.
	 */
	months_purchased: number;
	/**
	 * Note that this is unknowable on some platforms, like TikTok. In that case, it
	 * will always be 1.
	 */
	months_streak: number;
}
export declare interface UserUpdateEvent extends AbstractKoiEvent {
	event_type: 'USER_UPDATE';
	streamer: User;
}
export declare interface ViewerListEvent extends AbstractKoiEvent {
	event_type: 'VIEWER_LIST';
	viewers: User[];
}
export declare interface ViewerJoinLeaveEvent extends AbstractKoiEvent {
	event_type: 'VIEWER_JOIN' | 'VIEWER_LEAVE';
	viewer: User;
}
export declare interface ViewerCountEvent extends AbstractKoiEvent {
	event_type: 'VIEWER_COUNT';
	count: number;
}
/**
 * For RP_ACTION, see Twitch's /me command.
 */
export declare type MessageAttribute = 'HIGHLIGHTED' | 'RP_ACTION' | 'FIRST_TIME_CHATTER' | 'ANNOUNCEMENT';
export declare type MessageId = string;
export declare type MetaId = string;
export declare interface AbstractMessageMetaKoiEvent extends AbstractKoiEvent {
	meta_id: MetaId;
	is_visible: boolean;
	upvotes: number;
	attributes: MessageAttribute[];
}
export declare interface AbstractRichMessageEvent extends AbstractMessageMetaKoiEvent {
	sender: User;
	fragments: ChatFragment[];
	donations: Donation[];
	attachments: Attachment[];
	id: MessageId;
	reply_target: MetaId | null;
	raw: string;
	html: string;
}
export declare interface RichMessageEvent extends AbstractRichMessageEvent {
	event_type: 'RICH_MESSAGE';
}
export declare interface PlatformMessageEvent extends AbstractRichMessageEvent {
	event_type: 'PLATFORM_MESSAGE';
}
export declare type DonationType =
	| 'CASTERLABS_TEST'
	| 'OTHER'
	| 'CAFFEINE_PROP'
	| 'TWITCH_BITS'
	| 'TROVO_SPELL'
	| 'YOUTUBE_SUPER_CHAT'
	| 'YOUTUBE_SUPER_STICKER'
	| 'DLIVE_SUPER_CHAT'
	| 'DLIVE_LEMON'
	| 'TIKTOK_COINS';
export declare interface Donation {
	type: DonationType;
	name: string;
	currency: string;
	amount: number;
	/**
	 * This is the amount of the item sent. For example, Caffeine props can be sent
	 * multiple times in a single message. For the true value of a donation,
	 * multiply count by the amount.
	 */
	count: number;
	image: string;
}
export declare type AttachmentType = 'IMAGE' | 'INTERACTIVE';
export declare interface AttachmentContent {
	src: string;
	alt: string;
}
export declare interface Attachment {
	type: AttachmentType;
	content: AttachmentContent;
	html: string;
	donation: Donation | null;
}
export declare type ChatFragment = TextChatFragment | EmoteChatFragment | EmojiChatFragment | MentionChatFragment | LinkChatFragment;
export declare type ChatFragmentType = 'TEXT' | 'EMOTE' | 'EMOJI' | 'MENTION' | 'LINK';
export declare interface AbstractChatFragment {
	type: ChatFragmentType;
	raw: string;
	html: string;
}
export declare interface TextChatFragment extends AbstractChatFragment {
	type: 'TEXT';
	/**
	 * Same as raw.
	 */
	text: string;
}
export declare interface EmoteChatFragment extends AbstractChatFragment {
	type: 'EMOTE';
	emoteName: string;
	imageLink: string;
	/**
	 * Some emotes are purely for augmenting another emote. For instance, adding a
	 * rain effect on a Sad Pepe. This is already handled for you in the rendered
	 * html.
	 */
	isZeroWidth: boolean;
	provider: string | null;
	donation: Donation | null;
}
export declare interface EmojiChatFragment extends AbstractChatFragment {
	type: 'EMOJI';
	variation: any;
}
export declare interface MentionChatFragment extends AbstractChatFragment {
	type: 'MENTION';
	mentioned: User;
}
export declare interface LinkChatFragment extends AbstractChatFragment {
	type: 'LINK';
	url: string;
}
declare const GLOBAL$3: {
	readonly providers: any;
	readonly activePlayback: any;
};
declare function getCurrencies(): Promise<any>;
declare function formatCurrency(amount: number, currency: string): Promise<string>;
declare function convertCurrency(amount: number, from: string, to: string, formatResult?: boolean): Promise<string>;
declare const _default: {
	getCurrencies: typeof getCurrencies;
	formatCurrency: typeof formatCurrency;
	convertCurrency: typeof convertCurrency;
};
export declare interface AppSDK {
	readonly Koi: typeof GLOBAL$2;
	readonly Widget: typeof GLOBAL$1;
	readonly Music: typeof GLOBAL$3;
	readonly Currencies: typeof _default;
	readonly App: typeof GLOBAL;
	escapeHtml(unsafe: string): string;
	openLink(link: string): void;
}

export {};
