name: Deploy on Release

on:
  release:
    types: [created]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Compile the deploy helper.
        run: cd deploy-helper && bash ./mvnw clean package

      - name: Deploy the app.
        run: java -jar deploy-helper/target/deploy-helper.jar "${{ github.event_path }}"
