name: Deploy on Release

on:
  release:
    types: [created]

jobs:
  release-deploy:
    environment: "Configure Caffeinated Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Set deploy channel env.
        run: echo "DEPLOY_CHANNEL=${{ 'beta' && github.event.release.prerelease || 'stable' }}" >> $GITHUB_ENV

      - name: Compile the deploy helper.
        run: cd deploy-helper && bash ./mvnw clean package

      - name: Compile the app.
        run: bash build.sh nopackage

      - name: Package the app.
        run: bash build.sh nocompile

      - name: Deploy the app.
        run: java -jar deploy-helper/target/deploy-helper.jar "${{ github.event_path }}"
