name: Release Deploy

on:
  release:
    types: [created]

jobs:
  release-deploy:
    environment: "Caffeinated Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code.
        uses: actions/checkout@v3

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Set deploy channel env.
        run: echo "DEPLOY_CHANNEL=${{ (github.event.release.prerelease && 'beta') || 'stable' }}" >> $GITHUB_ENV

      - name: Compile the deploy helper.
        run: cd deploy-helper && bash ./mvnw clean package

      - name: Compile the app.
        run: bash build.sh nopackage

      - name: Package the app.
        run: bash build.sh nocompile

      - name: Deploy the app.
        env:
          BB_BUCKET_ID: ${{ secrets.BB_BUCKET_ID }}
          BB_CLIENT_ID: ${{ secrets.BB_CLIENT_ID }}
          BB_CLIENT_KEY: ${{ secrets.BB_CLIENT_KEY }}
        run: java -jar deploy-helper/target/deploy-helper.jar "${{ github.event_path }}"
